services:
  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    # environment:
    #   - DATABASE_URL=postgresql://representable:password@db/representable_db
    env_file:
      - .env
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true
  db:
    image: postgis/postgis:17-3.5-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=representable_db
      - POSTGRES_USER=representable
      - POSTGRES_PASSWORD=password
    volumes:
      - ./pg_data:/var/lib/postgresql/data
